texus -mn -o .3df -t rgb565 AV-Grass.tga
texus -mn -o .3df -t rgb565 AV-Road.tga
texus -mn -o .3df -t argb1555 RearTrees.tga
texus -mn -o .3df -t argb1555 AV-WhiteFence.tga
texus -mn -o .3df -t rgb565 AV-KilometreBoard.tga
texus -mn -o .3df -t rgb565 AV-KilometreBoard-1km.tga
texus -mn -o .3df -t argb1555 AV-AdvertBoard[AVUS].tga
texus -mn -o .3df -t argb1555 AV-TelegraphPole.tga
texus -mn -o .3df -t argb1555 AV-TelegraphPoleShadow.tga
texus -mn -o .3df -t argb1555 PineLowPolygonShadow.tga
texus -mn -o .3df -t argb1555 Pine[L].tga
texus -mn -o .3df -t argb1555 Pine[R].tga
texus -mn -o .3df -t argb1555 PineShadow.tga
texus -mn -o .3df -t rgb565 AV-Road-Turning.tga
texus -mn -o .3df -t argb1555 AV-SIgnPost.tga
texus -mn -o .3df -t rgb565 AV-Sign[Nikolasee].tga
texus -mn -o .3df -t rgb565 AV-Sign[Kaiserdamm].tga
texus -mn -o .3df -t rgb565 AV-Sign[Charlottenburg].tga
texus -mn -o .3df -t rgb565 AV-Road-Junction.tga
texus -mn -o .3df -t argb1555 av-bridgeconcrete.tga
texus -mn -o .3df -t rgb565 AV-BridgeConcreteShadow.tga
texus -mn -o .3df -t rgb565 AV-BridgeConcreteDark.tga
texus -mn -o .3df -t argb1555 AV-BridgeSteelSide.tga
texus -mn -o .3df -t argb1555 AV-MetalGrill.tga
