p:\boris\bin\tarcman track.tc -a AV-Grass.3df:3df-565 AV-Grass.3df
p:\boris\bin\tarcman track.tc -a AV-Road.3df:3df-565 AV-Road.3df
p:\boris\bin\tarcman track.tc -a RearTrees.3df:3df-1555 RearTrees.3df
p:\boris\bin\tarcman track.tc -a AV-WhiteFence.3df:3df-1555 AV-WhiteFence.3df
p:\boris\bin\tarcman track.tc -a AV-KilometreBoard.3df:3df-565 AV-KilometreBoard.3df
p:\boris\bin\tarcman track.tc -a AV-KilometreBoard-1km.3df:3df-565 AV-KilometreBoard-1km.3df
p:\boris\bin\tarcman track.tc -a AV-AdvertBoard[AVUS].3df:3df-1555 AV-AdvertBoard[AVUS].3df
p:\boris\bin\tarcman track.tc -a AV-TelegraphPole.3df:3df-1555 AV-TelegraphPole.3df
p:\boris\bin\tarcman track.tc -a AV-TelegraphPoleShadow.3df:3df-1555 AV-TelegraphPoleShadow.3df
p:\boris\bin\tarcman track.tc -a PineLowPolygonShadow.3df:3df-1555 PineLowPolygonShadow.3df
p:\boris\bin\tarcman track.tc -a Pine[L].3df:3df-1555 Pine[L].3df
p:\boris\bin\tarcman track.tc -a Pine[R].3df:3df-1555 Pine[R].3df
p:\boris\bin\tarcman track.tc -a PineShadow.3df:3df-1555 PineShadow.3df
p:\boris\bin\tarcman track.tc -a AV-Road-Turning.3df:3df-565 AV-Road-Turning.3df
p:\boris\bin\tarcman track.tc -a AV-SIgnPost.3df:3df-1555 AV-SIgnPost.3df
p:\boris\bin\tarcman track.tc -a AV-Sign[Nikolasee].3df:3df-565 AV-Sign[Nikolasee].3df
p:\boris\bin\tarcman track.tc -a AV-Sign[Kaiserdamm].3df:3df-565 AV-Sign[Kaiserdamm].3df
p:\boris\bin\tarcman track.tc -a AV-Sign[Charlottenburg].3df:3df-565 AV-Sign[Charlottenburg].3df
p:\boris\bin\tarcman track.tc -a AV-Road-Junction.3df:3df-565 AV-Road-Junction.3df
p:\boris\bin\tarcman track.tc -a av-bridgeconcrete.3df:3df-1555 av-bridgeconcrete.3df
p:\boris\bin\tarcman track.tc -a AV-BridgeConcreteShadow.3df:3df-565 AV-BridgeConcreteShadow.3df
p:\boris\bin\tarcman track.tc -a AV-BridgeConcreteDark.3df:3df-565 AV-BridgeConcreteDark.3df
p:\boris\bin\tarcman track.tc -a AV-BridgeSteelSide.3df:3df-1555 AV-BridgeSteelSide.3df
p:\boris\bin\tarcman track.tc -a AV-MetalGrill.3df:3df-1555 AV-MetalGrill.3df
