addtrans Ash[L]
addtrans Ash[R]
addshad AshShadow
addtrans Bush[L]
addtrans Bush[R]
addshad BushShadow
addtrans Pine[L]
addtrans Pine[R]
addshad PineShadow
addtrans RearTrees
addtex BackgroundLandscape
addtrans Shell-S&M
addtrans Bridgeside
addtex MetalGrill
addtex VicersBridgeShadow
addtrans DunlopSide
addtex ShellPagodaRoof
addtrans PitSide
addtex GrastandCrowd
addtex FlightTicketRoof
addtex PressHutSide
addtex JacksonSide
addtex ShellPagodaFront
addtrans ClubhouseFront
addtex ClubHouse2Side
addtex ClubHouseSide
addtex ClubhouseTower
addtex LBBmotorsSide
addtrans CambellShedFront
addtex CambellShedRoof&Side
addtex BPPagodaSide
addtex Bk-RoadSideGrass
addtex Bk-RoadSideGrass-Out
addtrans BK-Fence
addtex BK-RoadSurface
addtrans BK-RoadBridge
addtex BK-RoadBridgeSide
addtrans BK-WhiteFence
addtex BK-Concrete
addtex BK-RiverBank
addtex BK-River
addtex Bk-ConcreteWall
addtex BK-RockFace
addtrans BK-TelegraphPole
addshad BK-TelegraphPoleShadow
addtex VicersSideLogo
addtex VicersRoof
addtex VicersSide
addtex MotorRover
addtex HangerSide
addtex Shell-A-Cyl
addtex BrooklandsLogo
addtex BrickWall
addtex StartTower
addtex controlwall1

