pvrconv pausedit.tga -4 -nvm -v3
tarcman overlays.tc -a pausedit:3df-vq pausedit.pvr
pvrconv pausedfr.tga -4 -nvm -v3
tarcman overlays.tc -a pausedfr:3df-vq pausedfr.pvr
pvrconv pausedwe.tga -4 -nvm -v3
tarcman overlays.tc -a pausedwe:3df-vq pausedwe.pvr
pvrconv overlay10.tga -4 -nvm -v3
tarcman overlays.tc -a overlay10:3df-vq overlay10.pvr
pvrconv paused.tga -4 -nvm -v3
tarcman overlays.tc -a paused:3df-vq paused.pvr
pvrconv overlay10we.tga -4 -nvm -v3
tarcman overlays.tc -a overlay10we:3df-vq overlay10we.pvr
pvrconv overlay10ge.tga -4 -nvm -v3
tarcman overlays.tc -a overlay10ge:3df-vq overlay10ge.pvr
pvrconv pausedge.tga -4 -nvm -v3
tarcman overlays.tc -a pausedge:3df-vq pausedge.pvr
pvrconv overlay10it.tga -4 -nvm -v3
tarcman overlays.tc -a overlay10it:3df-vq overlay10it.pvr
pvrconv overlay00.tga -4 -nvm -v3
tarcman overlays.tc -a overlay00:3df-vq overlay00.pvr
pvrconv overlay01.tga -4 -nvm -v3
tarcman overlays.tc -a overlay01:3df-vq overlay01.pvr
pvrconv overlay11.tga -4 -nvm -v3
tarcman overlays.tc -a overlay11:3df-vq overlay11.pvr
pvrconv charfont.tga -4 -nvm -v3
tarcman overlays.tc -a charfont:3df-vq charfont.pvr
pvrconv overlay10fr.tga -4 -nvm -v3
tarcman overlays.tc -a overlay10fr:3df-vq overlay10fr.pvr
