copy wall17.3df e:
copy timetowertower1.3df e:
copy timingtowergallery01.3df e:
copy timetower01.3df e:
copy timetowerside.3df e:
copy pitsroof01.3df e:
copy PitsStones.3df e:
copy advAPL.3df e:
copy log01a.3df e:
copy advFinnis.3df e:
copy log08a.3df e:
copy advJJS.3df e:
copy log03a.3df e:
copy advReed.3df e:
copy advScurlock.3df e:
copy pitsside01.3df e:
copy pithole.3df e:
copy pitbrick01.3df e:
